name: test-manual
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        type: choice
        options:
          - info
          - warning
          - debug
        default: 'warning'
      deploy_env:
        description: 'deploy env'
        required: false
        type: choice
        options:
          - dev
          - test
          - prod
        default: 'dev'
      # build_id:
      #   description: 'build id'
      #   required: false
      #   type: number
      # print_tags:
      #   description: 'True to print to STDOUT'
      #   required: false
      #   type: boolean
      # tags:
      #   description: 'Test scenario tags'
      #   required: false
      #   type: string
      # environment:
      #   description: 'Environment to run tests against'
      #   required: false
      #   type: environment

jobs:
  dev-deploy:
    name: deplpy to dev server
    runs-on: ubuntu-18.04
    steps:
      - id: checkout
        name: checkou main
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build && Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: user/app:latest
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ secrets.ACTOR }}
      #     password: ${{ secrets.TOKEN_ACTION }}
      # - name: Build && Push
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     context: .
      #     file: Dockerfile
      #     tags: |
      #       ghcr.io/matrixone-cloud/auth-service:${{ github.event.inputs.tag }}
      #       ghcr.io/matrixone-cloud/auth-service:latest
